# Generated by Django 2.2 on 2022-03-23 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='developer',
            old_name='notion',
            new_name='tech',
        ),
    ]
